POKEMON = [
  "Abra", "Aerodactyl", "Aipom", "Alakazam", "Ampharos", "Arbok", "Arcanine",
  "Ariados", "Articuno", "Azumarill", "Bayleef", "Beedrill", "Bellossom",
  "Bellsprout", "Blastoise", "Blissey", "Bulbasaur", "Butterfree", "Caterpie",
  "Celebi", "Chansey", "Charizard", "Charmander", "Charmeleon", "Chikorita",
  "Chinchou", "Clefable", "Clefairy", "Cleffa", "Cloyster", "Corsola", "Crobat",
  "Croconaw", "Cubone", "Cyndaquil", "Delibird", "Dewgong", "Diglett", "Ditto",
  "Dodrio", "Doduo", "Donphan", "Dragonair", "Dragonite", "Dratini", "Drowzee",
  "Dugtrio", "Dunsparce", "Eevee", "Ekans", "Electabuzz", "Electrode", "Elekid",
  "Entei", "Espeon", "Exeggcute", "Exeggutor", "Farfetch D", "Fearow",
  "Feraligatr", "Flaaffy", "Flareon", "Forretress", "Furret", "Gastly",
  "Gengar", "Geodude", "Girafarig", "Gligar", "Gloom", "Golbat", "Goldeen",
  "Golduck", "Golem", "Granbull", "Graveler", "Grimer", "Growlithe", "Gyarados",
  "Haunter", "Heracross", "Hitmonchan", "Hitmonlee", "Hitmontop", "Ho Oh",
  "Hoothoot", "Hoppip", "Horsea", "Houndoom", "Houndour", "Hypno", "Igglybuff",
  "Ivysaur", "Jigglypuff", "Jolteon", "Jumpluff", "Jynx", "Kabuto", "Kabutops",
  "Kadabra", "Kakuna", "Kangaskhan", "Kingdra", "Kingler", "Koffing", "Krabby",
  "Lanturn", "Lapras", "Larvitar", "Ledian", "Ledyba", "Lickitung", "Lugia",
  "Machamp", "Machoke", "Machop", "Magby", "Magcargo", "Magikarp", "Magmar",
  "Magnemite", "Magneton", "Mankey", "Mantine", "Mareep", "Marill", "Marowak",
  "Meganium", "Meowth", "Metapod", "Mew", "Mewtwo", "Miltank", "Misdreavus",
  "Moltres", "Mr  Mime", "Muk", "Murkrow", "Natu", "Nidoking", "Nidoqueen",
  "Nidoran F", "Nidoran M", "Nidorina", "Nidorino", "Ninetales", "Noctowl",
  "Octillery", "Oddish", "Omanyte", "Omastar", "Onix", "Paras", "Parasect",
  "Persian", "Phanpy", "Pichu", "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu",
  "Piloswine", "Pineco", "Pinsir", "Politoed", "Poliwag", "Poliwhirl",
  "Poliwrath", "Ponyta", "Porygon", "Porygon2", "Primeape", "Psyduck",
  "Pupitar", "Quagsire", "Quilava", "Qwilfish", "Raichu", "Raikou", "Rapidash",
  "Raticate", "Rattata", "Remoraid", "Rhydon", "Rhyhorn", "Sandshrew",
  "Sandslash", "Scizor", "Scyther", "Seadra", "Seaking", "Seel", "Sentret",
  "Shellder", "Shuckle", "Skarmory", "Skiploom", "Slowbro", "Slowking",
  "Slowpoke", "Slugma", "Smeargle", "Smoochum", "Sneasel", "Snorlax",
  "Snubbull", "Spearow", "Spinarak", "Squirtle", "Stantler", "Starmie",
  "Staryu", "Steelix", "Sudowoodo", "Suicune", "Sunflora", "Sunkern", "Swinub",
  "Tangela", "Tauros", "Teddiursa", "Tentacool", "Tentacruel", "Togepi",
  "Togetic", "Totodile", "Typhlosion", "Tyranitar", "Tyrogue", "Umbreon",
  "Unown", "Ursaring", "Vaporeon", "Venomoth", "Venonat", "Venusaur",
  "Victreebel", "Vileplume", "Voltorb", "Vulpix", "Wartortle", "Weedle",
  "Weepinbell", "Weezing", "Wigglytuff", "Wobbuffet", "Wooper", "Xatu", "Yanma",
  "Zapdos", "Zubat"
]

MOVES = [
  "Absorb", "Acid", "Acid Armor", "Aeroblast", "Agility", "Amnesia",
  "Ancientpower", "Attract", "Aurora Beam", "Barrage", "Barrier", "Baton Pass",
  "Beat Up", "Belly Drum", "Bide", "Bind", "Bite", "Blizzard", "Body Slam",
  "Bone Club", "Bone Rush", "Bonemerang", "Bubble", "Bubblebeam", "Charm",
  "Clamp", "Comet Punch", "Confuse Ray", "Confusion", "Constrict", "Conversion",
  "Conversion2", "Cotton Spore", "Counter", "Crabhammer", "Cross Chop",
  "Crunch", "Curse", "Cut", "Defense Curl", "Destiny Bond", "Detect", "Dig",
  "Disable", "Dizzy Punch", "Double Edge", "Double Kick", "Double Team",
  "Doubleslap", "Dragon Rage", "Dragonbreath", "Dream Eater", "Drill Peck",
  "Dynamicpunch", "Earthquake", "Egg Bomb", "Ember", "Encore", "Endure",
  "Explosion", "Extremespeed", "Faint Attack", "False Swipe", "Fire Blast",
  "Fire Punch", "Fire Spin", "Fissure", "Flail", "Flame Wheel", "Flamethrower",
  "Flash", "Fly", "Focus Energy", "Foresight", "Frustration", "Fury Attack",
  "Fury Cutter", "Fury Swipes", "Future Sight", "Giga Drain", "Glare", "Growl",
  "Growth", "Guillotine", "Gust", "Harden", "Haze", "Headbutt", "Heal Bell",
  "Hi Jump Kick", "Hidden Power", "Horn Attack", "Horn Drill", "Hydro Pump",
  "Hyper Beam", "Hyper Fang", "Hypnosis", "Ice Beam", "Ice Punch", "Icy Wind",
  "Iron Tail", "Jump Kick", "Karate Chop", "Kinesis", "Leech Life",
  "Leech Seed", "Leer", "Lick", "Light Screen", "Lock On", "Lovely Kiss",
  "Low Kick", "Mach Punch", "Magnitude", "Mean Look", "Meditate", "Mega Drain",
  "Mega Kick", "Mega Punch", "Megahorn", "Metal Claw", "Metronome",
  "Milk Drink", "Mimic", "Mind Reader", "Minimize", "Mirror Coat",
  "Mirror Move", "Mist", "Moonlight", "Morning Sun", "Mud Slap", "Night Shade",
  "Nightmare", "No Move", "Octazooka", "Outrage", "Pain Split", "Pay Day",
  "Peck", "Perish Song", "Petal Dance", "Pin Missile", "Poison Gas",
  "Poison Sting", "Poisonpowder", "Pound", "Powder Snow", "Present", "Protect",
  "Psybeam", "Psych Up", "Psychic M", "Psywave", "Pursuit", "Quick Attack",
  "Rage", "Rain Dance", "Rapid Spin", "Razor Leaf", "Razor Wind", "Recover",
  "Reflect", "Rest", "Return", "Reversal", "Roar", "Rock Slide", "Rock Smash",
  "Rock Throw", "Rolling Kick", "Rollout", "Sacred Fire", "Safeguard",
  "Sand Attack", "Sandstorm", "Scary Face", "Scratch", "Screech",
  "Seismic Toss", "Selfdestruct", "Shadow Ball", "Sharpen", "Sing", "Sketch",
  "Skull Bash", "Sky Attack", "Slam", "Slash", "Sleep Powder", "Sleep Talk",
  "Sludge", "Sludge Bomb", "Smog", "Smokescreen", "Snore", "Softboiled",
  "Solarbeam", "Sonicboom", "Spark", "Spider Web", "Spike Cannon", "Spikes",
  "Spite", "Splash", "Spore", "Steel Wing", "Stomp", "Strength", "String Shot",
  "Struggle", "Stun Spore", "Submission", "Substitute", "Sunny Day",
  "Super Fang", "Supersonic", "Surf", "Swagger", "Sweet Kiss", "Sweet Scent",
  "Swift", "Swords Dance", "Synthesis", "Tackle", "Tail Whip", "Take Down",
  "Teleport", "Thief", "Thrash", "Thunder", "Thunder Wave", "Thunderbolt",
  "Thunderpunch", "Thundershock", "Toxic", "Transform", "Tri Attack",
  "Triple Kick", "Twineedle", "Twister", "Vicegrip", "Vine Whip", "Vital Throw",
  "Water Gun", "Waterfall", "Whirlpool", "Whirlwind", "Wing Attack", "Withdraw",
  "Wrap", "Zap Cannon"
]

ITEMS = [
  "No Item", "Master Ball", "Ultra Ball", "Brightpowder", "Great Ball",
  "Poke Ball", "Town Map", "Bicycle", "Moon Stone", "Antidote", "Burn Heal",
  "Ice Heal", "Awakening", "Parlyz Heal", "Full Restore", "Max Potion",
  "Hyper Potion", "Super Potion", "Potion", "Escape Rope", "Repel",
  "Max Elixer", "Fire Stone", "Thunderstone", "Water Stone", "Item 19", "Hp Up",
  "Protein", "Iron", "Carbos", "Lucky Punch", "Calcium", "Rare Candy",
  "X Accuracy", "Leaf Stone", "Metal Powder", "Nugget", "Poke Doll",
  "Full Heal", "Revive", "Max Revive", "Guard Spec", "Super Repel", "Max Repel",
  "Dire Hit", "Item 2D", "Fresh Water", "Soda Pop", "Lemonade", "X Attack",
  "Item 32", "X Defend", "X Speed", "X Special", "Coin Case", "Itemfinder",
  "Poke Flute", "Exp Share", "Old Rod", "Good Rod", "Silver Leaf", "Super Rod",
  "Pp Up", "Ether", "Max Ether", "Elixer", "Red Scale", "Secretpotion",
  "S S Ticket", "Mystery Egg", "Clear Bell", "Silver Wing", "Moomoo Milk",
  "Quick Claw", "Psncureberry", "Gold Leaf", "Soft Sand", "Sharp Beak",
  "Przcureberry", "Burnt Berry", "Ice Berry", "Poison Barb", "Kings Rock",
  "Bitter Berry", "Mint Berry", "Red Apricorn", "Tinymushroom", "Big Mushroom",
  "Silverpowder", "Blu Apricorn", "Item 5A", "Amulet Coin", "Ylw Apricorn",
  "Grn Apricorn", "Cleanse Tag", "Mystic Water", "Twistedspoon", "Wht Apricorn",
  "Blackbelt I", "Blk Apricorn", "Item 64", "Pnk Apricorn", "Blackglasses",
  "Slowpoketail", "Pink Bow", "Stick", "Smoke Ball", "Nevermeltice", "Magnet",
  "Miracleberry", "Pearl", "Big Pearl", "Everstone", "Spell Tag",
  "Ragecandybar", "Gs Ball", "Blue Card", "Miracle Seed", "Thick Club",
  "Focus Band", "Item 78", "Energypowder", "Energy Root", "Heal Powder",
  "Revival Herb", "Hard Stone", "Lucky Egg", "Card Key", "Machine Part",
  "Egg Ticket", "Lost Item", "Stardust", "Star Piece", "Basement Key", "Pass",
  "Item 87", "Item 88", "Item 89", "Charcoal", "Berry Juice", "Scope Lens",
  "Item 8D", "Item 8E", "Metal Coat", "Dragon Fang", "Item 91", "Leftovers",
  "Item 93", "Item 94", "Item 95", "Mysteryberry", "Dragon Scale",
  "Berserk Gene", "Item 99", "Item 9A", "Item 9B", "Sacred Ash", "Heavy Ball",
  "Flower Mail", "Level Ball", "Lure Ball", "Fast Ball", "Item A2",
  "Light Ball", "Friend Ball", "Moon Ball", "Love Ball", "Normal Box",
  "Gorgeous Box", "Sun Stone", "Polkadot Bow", "Item AB", "Up Grade", "Berry",
  "Gold Berry", "Squirtbottle", "Item B0", "Park Ball", "Rainbow Wing",
  "Item B3", "Brick Piece", "Surf Mail", "Litebluemail", "Portraitmail",
  "Lovely Mail", "Eon Mail", "Morph Mail", "Bluesky Mail", "Music Mail",
  "Mirage Mail", "Item BE"
]

JOHTO_ROUTES = [
  "BLACKTHORN_CITY", "BURNED_TOWER_1F", "BURNED_TOWER_B1F", "CHERRYGROVE_CITY",
  "CIANWOOD_CITY", "DARK_CAVE_BLACKTHORN_ENTRANCE", "DARK_CAVE_VIOLET_ENTRANCE",
  "DRAGONS_DEN_B1F", "ECRUTEAK_CITY", "ICE_PATH_1F", "ICE_PATH_B1F",
  "ICE_PATH_B2F_BLACKTHORN_SIDE", "ICE_PATH_B2F_MAHOGANY_SIDE", "ICE_PATH_B3F",
  "ILEX_FOREST", "LAKE_OF_RAGE", "MOUNT_MORTAR_1F_INSIDE",
  "MOUNT_MORTAR_1F_OUTSIDE", "MOUNT_MORTAR_2F_INSIDE", "MOUNT_MORTAR_B1F",
  "NATIONAL_PARK", "NEW_BARK_TOWN", "OLIVINE_CITY", "OLIVINE_PORT", "ROUTE_29",
  "ROUTE_30", "ROUTE_31", "ROUTE_32", "ROUTE_33", "ROUTE_34", "ROUTE_35",
  "ROUTE_36", "ROUTE_37", "ROUTE_38", "ROUTE_39", "ROUTE_40", "ROUTE_41",
  "ROUTE_42", "ROUTE_43", "ROUTE_44", "ROUTE_45", "ROUTE_46",
  "RUINS_OF_ALPH_INNER_CHAMBER", "RUINS_OF_ALPH_OUTSIDE",
  "SILVER_CAVE_ITEM_ROOMS", "SILVER_CAVE_OUTSIDE", "SILVER_CAVE_ROOM_1",
  "SILVER_CAVE_ROOM_2", "SILVER_CAVE_ROOM_3", "SLOWPOKE_WELL_B1F",
  "SLOWPOKE_WELL_B2F", "SPROUT_TOWER_2F", "SPROUT_TOWER_3F", "TIN_TOWER_2F",
  "TIN_TOWER_3F", "TIN_TOWER_4F", "TIN_TOWER_5F", "TIN_TOWER_6F", "TIN_TOWER_7F",
  "TIN_TOWER_8F", "TIN_TOWER_9F", "UNION_CAVE_1F", "UNION_CAVE_B1F",
  "UNION_CAVE_B2F", "VIOLET_CITY", "WHIRL_ISLAND_B1F", "WHIRL_ISLAND_B2F",
  "WHIRL_ISLAND_CAVE", "WHIRL_ISLAND_LUGIA_CHAMBER", "WHIRL_ISLAND_NE",
  "WHIRL_ISLAND_NW", "WHIRL_ISLAND_SE", "WHIRL_ISLAND_SW"
]

KANTO_ROUTES = [
  "DIGLETTS_CAVE", "MOUNT_MOON", "ROCK_TUNNEL_1F", "ROCK_TUNNEL_B1F",
  "VICTORY_ROAD", "TOHJO_FALLS", "ROUTE_1", "ROUTE_2", "ROUTE_3", "ROUTE_4",
  "ROUTE_5", "ROUTE_6", "ROUTE_7", "ROUTE_8", "ROUTE_9", "ROUTE_10_NORTH",
  "ROUTE_11", "ROUTE_13", "ROUTE_14", "ROUTE_15", "ROUTE_16", "ROUTE_17",
  "ROUTE_18", "ROUTE_21", "ROUTE_22", "ROUTE_24", "ROUTE_25", "ROUTE_26",
  "ROUTE_27", "ROUTE_28", "TOHJO_FALLS", "VERMILION_PORT", "ROUTE_4", "ROUTE_6",
  "ROUTE_9", "ROUTE_10_NORTH", "ROUTE_12", "ROUTE_13", "ROUTE_19", "ROUTE_20",
  "ROUTE_21", "ROUTE_22", "ROUTE_24", "ROUTE_25", "ROUTE_26", "ROUTE_27",
  "ROUTE_28", "PALLET_TOWN", "VIRIDIAN_CITY", "CERULEAN_CITY", "VERMILION_CITY",
  "CELADON_CITY", "FUCHSIA_CITY", "CINNABAR_ISLAND"
]

def convert_data_name(string):
  return string.upper().replace(' ', '_')